### ISSUE TITLE
"Unexpected end of JSON input"

### ISSUE THREAD

**Issue by loshprung** [maddiewaldie/COEN-174-Project#54]
Regression from #53 causes signup and login to fail

Login failure is:
- `LogIn.js:45 error SyntaxError: Unexpected end of JSON input`

Signup failure is:
- `SignUp.js:55 error SyntaxError: Unexpected end of JSON input`
